### ISSUE TITLE
Is there a limit to how many projects can be displayed?

### ISSUE THREAD

**Issue by bulentyusuf** [EmaSuriano/gatsby-theme-mate#43]
I just added a fourth project but it's only showing the last three in the project section.

here's the site: https://getsomejam.net/#projects

here's the fork: https://github.com/bulentyusuf/gatsby-starter-mate

**Comment by EmaSuriano** [comment]
The projects are coming from this [query](https://github.com/EmaSuriano/gatsby-theme-mate/blob/master/gatsby-theme-mate/src/queries/useProjectsQuery.ts), so in theory there is no constraint :)
