### ISSUE TITLE
Add feature to update Footer text via Contentful

### ISSUE THREAD

**Issue by srajac** [EmaSuriano/gatsby-theme-mate#7]
At the moment the Footer text is set to "{name} Portfolio - Powered by Gatsby, Contentful, Netlify" by default.  There is currently no parameterised way to customise this.

It would be good to add a feature that allows the web developer to update the Footer using Contentful so we can customise the footer text if we don't want to use the default.

**Comment by EmaSuriano** [comment]
Hey @srajac sorry for the late response. You can easily replace any of the component from the starter, by using [theme-shadowing](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/). Therefore in case you want to update the Footer with your content just create a file inside `src/gatsby-theme-mate/components/Footer.js` and inside you can render whatever you want 👍
